development:
  adapter: postgresql
  database: angularjs_demo_development
  encoding: utf8
  pool: 5
  host: localhost
  port: 5432

test:
  adapter: postgresql
  database: angularjs_demo_test
  encoding: utf8
  pool: 5
  host: localhost
  port: 5432
